AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  assignment-backend

  Sample SAM Template for assignment declaration backend

Globals:
  Function:
    Timeout: 60

Resources:
  ListDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.list_data
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        ListData:
          Type: Api
          Properties:
            Path: /api/list
            Method: get
  SubmitFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.submit_form
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        SubmitForm:
          Type: Api
          Properties:
            Path: /api/form/submit
            Method: post
        

Outputs:
  SubmitFormApi:
    Description: "API Gateway endpoint URL for Prod stage for form submission"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/form/submit"
  ListData:
    Description: "API Gateway endpoint URL for Prod stage for data listing"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/list"
